site_name: Project-Archimedes Documentation
site_url: https://thecodinglaplace.com.br/docs/
theme: 
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: deep orange

nav:
  - Home: index.md

